# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Telemetry.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='Telemetry.proto',
  package='',
  syntax='proto3',
  serialized_options=b'\252\002\034ConformaceGrpcService.Protos',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fTelemetry.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x8a\x05\n\tTelemetry\x12\x14\n\x0coperation_id\x18\x01 \x01(\t\x12\x1c\n\x14\x65nroute_positions_id\x18\x02 \x01(\t\x12\x17\n\x0fregistration_id\x18\x03 \x01(\t\x12\x18\n\x10reference_number\x18\x04 \x01(\t\x12\'\n\x08location\x18\x05 \x01(\x0b\x32\x15.Telemetry.PointModel\x12\x17\n\x0fground_speed_kt\x18\x06 \x01(\x01\x12\x15\n\rtime_measured\x18\x07 \x01(\x03\x12\x11\n\ttime_send\x18\x08 \x01(\x03\x12\x19\n\x11\x62\x61ttery_remaining\x18\t \x01(\x05\x12\x0c\n\x04mode\x18\n \x01(\t\x12\x19\n\x11\x61ltitude_ft_wgs84\x18\x0b \x01(\x01\x12#\n\x1b\x61ltitude_num_gps_satellites\x18\x0c \x01(\x05\x12\x10\n\x08hdop_gps\x18\r \x01(\x01\x12\x19\n\x11track_bearing_deg\x18\x0e \x01(\x01\x12\x41\n\x17track_bearing_reference\x18\x0f \x01(\x0e\x32 .Telemetry.TrackBearingReference\x12\x10\n\x08vdop_gps\x18\x10 \x01(\x01\x12\x0c\n\x04roll\x18\x11 \x01(\x01\x12\x0b\n\x03yaw\x18\x12 \x01(\x01\x12\r\n\x05pitch\x18\x13 \x01(\x01\x12\x11\n\tclimbrate\x18\x14 \x01(\x01\x12\x0f\n\x07heading\x18\x15 \x01(\x01\x1a\x34\n\nPointModel\x12\x0c\n\x04type\x18\x01 \x01(\t\x12\x0b\n\x03lat\x18\x02 \x01(\x01\x12\x0b\n\x03lng\x18\x03 \x01(\x01\";\n\x15TrackBearingReference\x12\x0e\n\nTRUE_NORTH\x10\x00\x12\x12\n\x0eMAGNETIC_NORTH\x10\x01\x32H\n\x0fTelemetryModule\x12\x35\n\rPostTelemetry\x12\n.Telemetry\x1a\x16.google.protobuf.Empty(\x01\x42\x1f\xaa\x02\x1c\x43onformaceGrpcService.Protosb\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])



_TELEMETRY_TRACKBEARINGREFERENCE = _descriptor.EnumDescriptor(
  name='TrackBearingReference',
  full_name='Telemetry.TrackBearingReference',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='TRUE_NORTH', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='MAGNETIC_NORTH', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=640,
  serialized_end=699,
)
_sym_db.RegisterEnumDescriptor(_TELEMETRY_TRACKBEARINGREFERENCE)


_TELEMETRY_POINTMODEL = _descriptor.Descriptor(
  name='PointModel',
  full_name='Telemetry.PointModel',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='type', full_name='Telemetry.PointModel.type', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lat', full_name='Telemetry.PointModel.lat', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='lng', full_name='Telemetry.PointModel.lng', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=586,
  serialized_end=638,
)

_TELEMETRY = _descriptor.Descriptor(
  name='Telemetry',
  full_name='Telemetry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='operation_id', full_name='Telemetry.operation_id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='enroute_positions_id', full_name='Telemetry.enroute_positions_id', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='registration_id', full_name='Telemetry.registration_id', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='reference_number', full_name='Telemetry.reference_number', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='location', full_name='Telemetry.location', index=4,
      number=5, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ground_speed_kt', full_name='Telemetry.ground_speed_kt', index=5,
      number=6, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time_measured', full_name='Telemetry.time_measured', index=6,
      number=7, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='time_send', full_name='Telemetry.time_send', index=7,
      number=8, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='battery_remaining', full_name='Telemetry.battery_remaining', index=8,
      number=9, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='mode', full_name='Telemetry.mode', index=9,
      number=10, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='altitude_ft_wgs84', full_name='Telemetry.altitude_ft_wgs84', index=10,
      number=11, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='altitude_num_gps_satellites', full_name='Telemetry.altitude_num_gps_satellites', index=11,
      number=12, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='hdop_gps', full_name='Telemetry.hdop_gps', index=12,
      number=13, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='track_bearing_deg', full_name='Telemetry.track_bearing_deg', index=13,
      number=14, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='track_bearing_reference', full_name='Telemetry.track_bearing_reference', index=14,
      number=15, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='vdop_gps', full_name='Telemetry.vdop_gps', index=15,
      number=16, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='roll', full_name='Telemetry.roll', index=16,
      number=17, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='yaw', full_name='Telemetry.yaw', index=17,
      number=18, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pitch', full_name='Telemetry.pitch', index=18,
      number=19, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='climbrate', full_name='Telemetry.climbrate', index=19,
      number=20, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='heading', full_name='Telemetry.heading', index=20,
      number=21, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_TELEMETRY_POINTMODEL, ],
  enum_types=[
    _TELEMETRY_TRACKBEARINGREFERENCE,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=49,
  serialized_end=699,
)

_TELEMETRY_POINTMODEL.containing_type = _TELEMETRY
_TELEMETRY.fields_by_name['location'].message_type = _TELEMETRY_POINTMODEL
_TELEMETRY.fields_by_name['track_bearing_reference'].enum_type = _TELEMETRY_TRACKBEARINGREFERENCE
_TELEMETRY_TRACKBEARINGREFERENCE.containing_type = _TELEMETRY
DESCRIPTOR.message_types_by_name['Telemetry'] = _TELEMETRY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Telemetry = _reflection.GeneratedProtocolMessageType('Telemetry', (_message.Message,), {

  'PointModel' : _reflection.GeneratedProtocolMessageType('PointModel', (_message.Message,), {
    'DESCRIPTOR' : _TELEMETRY_POINTMODEL,
    '__module__' : 'Telemetry_pb2'
    # @@protoc_insertion_point(class_scope:Telemetry.PointModel)
    })
  ,
  'DESCRIPTOR' : _TELEMETRY,
  '__module__' : 'Telemetry_pb2'
  # @@protoc_insertion_point(class_scope:Telemetry)
  })
_sym_db.RegisterMessage(Telemetry)
_sym_db.RegisterMessage(Telemetry.PointModel)


DESCRIPTOR._options = None

_TELEMETRYMODULE = _descriptor.ServiceDescriptor(
  name='TelemetryModule',
  full_name='TelemetryModule',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=701,
  serialized_end=773,
  methods=[
  _descriptor.MethodDescriptor(
    name='PostTelemetry',
    full_name='TelemetryModule.PostTelemetry',
    index=0,
    containing_service=None,
    input_type=_TELEMETRY,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_TELEMETRYMODULE)

DESCRIPTOR.services_by_name['TelemetryModule'] = _TELEMETRYMODULE

# @@protoc_insertion_point(module_scope)
