#!/bin/sh
#
# @name 3DR Iris Quadrotor SITL
#
# @type Quadrotor Wide
#
# @maintainer Julian Oes <julian@oes.ch>
#

. ${R}etc/init.d/rc.mc_defaults

# Publish only primary mag
#param set SENS_MAG_MODE 0
# Use only 1 EKF instance (easier debugging)
#param set EKF2_MULTI_IMU 4
#param set EKF2_MULTI_MAG 2 
param set SYS_HITL 0
param set BAT1_SOURCE 1 # external battery info
param set EKF2_AID_MASK 1  
param set EKF2_MAG_TYPE 0 
param set EKF2_SYNT_MAG_Z 1
param set EKF2_MAG_CHECK 1
param set MIS_MNT_YAW_CTL 1
param set MC_ROLLRATE_K 1 
param set MC_ROLLRATE_D 0.006  #0.0090 
param set MC_ROLLRATE_I 0.300 

param set MC_PITCHRATE_K 1 
param set MC_PITCHRATE_D 0.006 #0.0090 
param set MC_PITCHRATE_I 0.300 

param set MC_YAWRATE_K 1 
param set MC_YAWRATE_I 0.10 

param set THR_MDL_FAC 1.000
param set MPC_USE_HTE 1.000
param set MPC_THR_HOVER 0.50

param set MC_AIRMODE 0.000

param set IMU_GYRO_RATEMAX 0
param set IMU_INTEG_RATE 250
param set SDLOG_PROFILE 0 

param set IMU_GYRO_CUTOFF 70.000
param set IMU_DGYRO_CUTOFF 30.000
param set IMU_ACCEL_CUTOFF 30.000

param set MPC_POS_MODE 3 
param set MPC_THR_MIN 0.12
#param set EKF2_BCOEF_X 0
#param set EKF2_BCOEF_Y 0
param set EKF2_GND_EFF_DZ 0
#param set EKF2_MCOEF 0

param set EKF2_GPS_V_NOISE 0.2
param set EKF2_GPS_P_NOISE 0.2
param set MPC_XY_CRUISE 20

param set MPC_YAW_MODE 3
set MIXER quad_x
set PWM_OUT 1234 






